# Generated by Django 5.0.4 on 2024-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotkeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('keyword_date', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
