# Generated by Django 5.0.4 on 2024-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotkeywords',
            name='keyword_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
