# Generated by Django 5.0.4 on 2024-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hotkeywords_keyword_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailykeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('keyword_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
