# Generated by Django 5.0.4 on 2024-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailykeyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dailykeyword',
            new_name='Dailykeywords',
        ),
    ]
