# Generated by Django 5.0.4 on 2024-04-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dailykeyword_dailykeywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordclouds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordcloud_date', models.DateTimeField(auto_now_add=True)),
                ('wordcloud_img', models.ImageField(null=True, upload_to='hotkeyword')),
            ],
        ),
    ]
